SELECT CURRENT_TIMESTAMP

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT SYSDATETIME()

SELECT DATEADD(DAY,5,GETDATE())

SELECT DATEDIFF(MONTH, '20200101', '20201231') 

SELECT DATEFROMPARTS(2020,10,20)

SELECT DATENAME(YEAR,GETDATE()),DATENAME(MONTH,GETDATE()),DATENAME(DAY,GETDATE()),DATENAME(WEEKDAY,GETDATE())

SELECT DATEPART(DAY, GETDATE()),DATEPART(WEEKDAY, GETDATE())

SELECT DAY(GETDATE()),MONTH(GETDATE()),YEAR(GETDATE())

SELECT ISDATE('20203112'),ISDATE('20201231')

